version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: bundle update
          command: gem install bundler:1.17.2
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies 
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          paths:
            - ./node_modules
          keys:
            - v2-dependencies-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            - v2-dependencies-
      - run:
          name: Execute check
          command: |
            #bundle exec rubocop
            bundle exec rspec
            #curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --1.22.4
            #yarn install --check-files
            #bundle exec rake db:setup
            #bundle exec rspec
