version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers-legacy
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          MYSQL_USER: 'msuser'
          MYSQL_ROOT_PASSWORD: 'passwd'
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: 'knowledgeApp_test'
          MYSQL_USER: 'msuser'
          MYSQL_ROOT_PASSWORD: 'passwd'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create --trace
      - run: bundle exec rake db:schema:load
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

# workflows:
 #  version: 2
#   rubocop_rails:
  #   jobs:
    #  - rubocop
    #   - rspec:
     #     requires:
     #       - rubocop
            #curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --1.22.4
            #yarn install --check-files
            #bundle exec rake db:setup
            #bundle exec rspec
